baseURL = 'https://sujtfri.github.io/'
theme = ["hugo-cloak-email", "sujt_theme"]
relativeURLs = true
paginate = 3

[params]
rootURL = "https://sujtfri.github.io/"


[languages]
  [languages.en]
    title = 'SUJT'
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
    [languages.en.params]
      flag = "flag-icon-us"
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "Home"
        url = "/"
        weight = 100
        identifier = "home"  

      [[languages.en.menus.main]]
        name = "Members"
        url = "/members/"
        weight = 200
      
      [[languages.en.menus.main]]
        name = "Research"
        url = "/research/"
        weight = 300
        identifier = "research"   

      
      [[languages.en.menus.main]]
        name = "Blog and news"
        url = "/blog/"
        weight = 400

      [[languages.en.menus.main]]
        name = "Media center"
        url = "/media/"
        weight = 400


  [languages.si]
        title = 'SUJT'
        contentDir = 'content/slovene'
        languageName = 'Slovenščina'
        weight = 20
        [languages.si.params]
          flag = "flag-icon-si"
      [languages.si.menus]
          [[languages.si.menus.main]]
            name = "Domov"
            url = "/si/"
            weight = 100
            identifier = "home"  

            [[languages.si.menus.main]]
            name = "Člani"
            url = "/si/members/"
            weight = 200
            
            [[languages.si.menus.main]]
            name = "Raziskave"
            url = "/si/research/"
            weight = 300
            identifier = "research"  
            
            [[languages.si.menus.main]]
            name = "Blog in novice"
            url = "/si/blog/"
            weight = 400

            [[languages.si.menus.main]]
            name = "Medijsko središče"
            url = "/si/media/"
            weight = 500
         

[markup.goldmark.renderer] 
  unsafe= true
  